import { Deal, Conflict, SyncEvent, FieldMapping } from '@/types/dealsync';

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-001',
    name: 'Enterprise Cloud Migration',
    company: 'Acme Technologies',
    stage: 'Negotiation',
    amount: 120000,
    owner: 'Sarah Connor',
    expectedClose: '2026-10-15',
    hubspotId: 'hs-deal-90812',
    notionPageId: 'notion-page-4401a',
    hubspotStatus: 'modified',
    notionStatus: 'modified',
    syncStatus: 'Conflict',
    lastSyncedAt: '12 mins ago',
    hubspotAmount: 120000,
    notionAmount: 115000,
    hubspotStage: 'Negotiation',
    notionStage: 'Negotiation',
    hubspotCloseDate: '2026-10-15',
    notionCloseDate: '2026-10-20'
  },
  {
    id: 'deal-002',
    name: 'Data Analytics Platform',
    company: 'Globex Industries',
    stage: 'Proposal',
    amount: 85000,
    owner: 'Marcus Vance',
    expectedClose: '2026-10-28',
    hubspotId: 'hs-deal-88231',
    notionPageId: 'notion-page-5512b',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '24 mins ago',
    hubspotAmount: 85000,
    notionAmount: 85000,
    hubspotStage: 'Proposal',
    notionStage: 'Proposal'
  },
  {
    id: 'deal-003',
    name: 'Fleet Management System',
    company: 'Stark Logistics',
    stage: 'Qualified',
    amount: 200000,
    owner: 'Elena Rostova',
    expectedClose: '2026-11-05',
    hubspotId: 'hs-deal-77419',
    notionPageId: 'notion-page-6623c',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '1 hour ago',
    hubspotAmount: 200000,
    notionAmount: 200000,
    hubspotStage: 'Qualified',
    notionStage: 'Qualified'
  },
  {
    id: 'deal-004',
    name: 'Cybersecurity Implementation',
    company: 'Wayne Enterprises',
    stage: 'New Lead',
    amount: 75000,
    owner: 'David Zhao',
    expectedClose: '2026-11-20',
    hubspotId: 'hs-deal-66324',
    notionPageId: 'notion-page-7734d',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '2 hours ago',
    hubspotAmount: 75000,
    notionAmount: 75000,
    hubspotStage: 'New Lead',
    notionStage: 'New Lead'
  },
  {
    id: 'deal-005',
    name: 'AI Infrastructure Contract',
    company: 'Cyberdyne Systems',
    stage: 'Negotiation',
    amount: 150000,
    owner: 'Sarah Connor',
    expectedClose: '2026-10-18',
    hubspotId: 'hs-deal-55431',
    notionPageId: 'notion-page-8845e',
    hubspotStatus: 'modified',
    notionStatus: 'modified',
    syncStatus: 'Conflict',
    lastSyncedAt: '35 mins ago',
    hubspotAmount: 150000,
    notionAmount: 150000,
    hubspotStage: 'Negotiation',
    notionStage: 'Proposal'
  },
  {
    id: 'deal-006',
    name: 'Supply Chain Platform',
    company: 'Umbrella Solutions',
    stage: 'Proposal',
    amount: 95000,
    owner: 'Marcus Vance',
    expectedClose: '2026-11-12',
    hubspotId: 'hs-deal-44567',
    notionPageId: 'notion-page-9956f',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '3 hours ago',
    hubspotAmount: 95000,
    notionAmount: 95000,
    hubspotStage: 'Proposal',
    notionStage: 'Proposal'
  },
  {
    id: 'deal-007',
    name: 'Enterprise Support Contract',
    company: 'Acme Technologies',
    stage: 'Qualified',
    amount: 60000,
    owner: 'Elena Rostova',
    expectedClose: '2026-12-01',
    hubspotId: 'hs-deal-33678',
    notionPageId: 'notion-page-1167g',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '4 hours ago',
    hubspotAmount: 60000,
    notionAmount: 60000,
    hubspotStage: 'Qualified',
    notionStage: 'Qualified'
  },
  {
    id: 'deal-008',
    name: 'Logistics Automation',
    company: 'Stark Logistics',
    stage: 'Closed Won',
    amount: 180000,
    owner: 'Elena Rostova',
    expectedClose: '2026-09-15',
    hubspotId: 'hs-deal-22789',
    notionPageId: 'notion-page-2278h',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '5 hours ago',
    hubspotAmount: 180000,
    notionAmount: 180000,
    hubspotStage: 'Closed Won',
    notionStage: 'Closed Won'
  },
  {
    id: 'deal-009',
    name: 'Security Monitoring Platform',
    company: 'Wayne Enterprises',
    stage: 'Closed Won',
    amount: 110000,
    owner: 'David Zhao',
    expectedClose: '2026-09-10',
    hubspotId: 'hs-deal-11890',
    notionPageId: 'notion-page-3389i',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '6 hours ago',
    hubspotAmount: 110000,
    notionAmount: 110000,
    hubspotStage: 'Closed Won',
    notionStage: 'Closed Won'
  },
  {
    id: 'deal-010',
    name: 'Machine Learning Platform',
    company: 'Cyberdyne Systems',
    stage: 'Closed Lost',
    amount: 250000,
    owner: 'Sarah Connor',
    expectedClose: '2026-09-02',
    hubspotId: 'hs-deal-00901',
    notionPageId: 'notion-page-4490j',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '1 day ago',
    hubspotAmount: 250000,
    notionAmount: 250000,
    hubspotStage: 'Closed Lost',
    notionStage: 'Closed Lost'
  },
  {
    id: 'deal-011',
    name: 'Cloud Security Upgrade',
    company: 'Globex Industries',
    stage: 'Proposal',
    amount: 135000,
    owner: 'Marcus Vance',
    expectedClose: '2026-10-30',
    hubspotId: 'hs-deal-99012',
    notionPageId: 'notion-page-5501k',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '1 day ago',
    hubspotAmount: 135000,
    notionAmount: 135000,
    hubspotStage: 'Proposal',
    notionStage: 'Proposal'
  },
  {
    id: 'deal-012',
    name: 'Warehouse Automation',
    company: 'Umbrella Solutions',
    stage: 'Negotiation',
    amount: 175000,
    owner: 'David Zhao',
    expectedClose: '2026-11-18',
    hubspotId: 'hs-deal-88123',
    notionPageId: 'notion-page-6612l',
    hubspotStatus: 'pending',
    notionStatus: 'synced',
    syncStatus: 'Pending',
    lastSyncedAt: 'Just now',
    hubspotAmount: 175000,
    notionAmount: 175000,
    hubspotStage: 'Negotiation',
    notionStage: 'Negotiation'
  },
  // Additional deals to round out the 24 deals dataset
  {
    id: 'deal-013',
    name: 'Global SD-WAN Rollout',
    company: 'Massive Dynamic',
    stage: 'Proposal',
    amount: 220000,
    owner: 'Elena Rostova',
    expectedClose: '2026-11-25',
    hubspotId: 'hs-deal-77234',
    notionPageId: 'notion-page-7723m',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '1 day ago',
    hubspotAmount: 220000,
    notionAmount: 220000,
    hubspotStage: 'Proposal',
    notionStage: 'Proposal'
  },
  {
    id: 'deal-014',
    name: 'Zero Trust Network Access',
    company: 'Initech Global',
    stage: 'Qualified',
    amount: 92000,
    owner: 'Marcus Vance',
    expectedClose: '2026-12-10',
    hubspotId: 'hs-deal-66345',
    notionPageId: 'notion-page-8834n',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '2 days ago',
    hubspotAmount: 92000,
    notionAmount: 92000,
    hubspotStage: 'Qualified',
    notionStage: 'Qualified'
  },
  {
    id: 'deal-015',
    name: 'Customer Data Platform',
    company: 'Hooli Tech',
    stage: 'Negotiation',
    amount: 165000,
    owner: 'Sarah Connor',
    expectedClose: '2026-10-22',
    hubspotId: 'hs-deal-55456',
    notionPageId: 'notion-page-9945o',
    hubspotStatus: 'error',
    notionStatus: 'synced',
    syncStatus: 'Failed',
    lastSyncedAt: '1 hour ago',
    hubspotAmount: 165000,
    notionAmount: 165000,
    hubspotStage: 'Negotiation',
    notionStage: 'Negotiation'
  },
  {
    id: 'deal-016',
    name: 'Edge Computing Gateway',
    company: 'Soylent Corp',
    stage: 'New Lead',
    amount: 65000,
    owner: 'David Zhao',
    expectedClose: '2026-12-15',
    hubspotId: 'hs-deal-44567-b',
    notionPageId: 'notion-page-1156p',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '2 days ago',
    hubspotAmount: 65000,
    notionAmount: 65000,
    hubspotStage: 'New Lead',
    notionStage: 'New Lead'
  },
  {
    id: 'deal-017',
    name: 'Predictive Analytics Suite',
    company: 'Weyland-Yutani',
    stage: 'Proposal',
    amount: 310000,
    owner: 'Sarah Connor',
    expectedClose: '2026-11-30',
    hubspotId: 'hs-deal-33678-b',
    notionPageId: 'notion-page-2267q',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '2 days ago',
    hubspotAmount: 310000,
    notionAmount: 310000,
    hubspotStage: 'Proposal',
    notionStage: 'Proposal'
  },
  {
    id: 'deal-018',
    name: 'Identity Governance Suite',
    company: 'Tyrell Corporation',
    stage: 'Closed Won',
    amount: 195000,
    owner: 'Elena Rostova',
    expectedClose: '2026-08-28',
    hubspotId: 'hs-deal-22789-b',
    notionPageId: 'notion-page-3378r',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '3 days ago',
    hubspotAmount: 195000,
    notionAmount: 195000,
    hubspotStage: 'Closed Won',
    notionStage: 'Closed Won'
  },
  {
    id: 'deal-019',
    name: 'API Management Hub',
    company: 'Oscorp Industries',
    stage: 'Qualified',
    amount: 88000,
    owner: 'Marcus Vance',
    expectedClose: '2026-11-15',
    hubspotId: 'hs-deal-11890-b',
    notionPageId: 'notion-page-4489s',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '3 days ago',
    hubspotAmount: 88000,
    notionAmount: 88000,
    hubspotStage: 'Qualified',
    notionStage: 'Qualified'
  },
  {
    id: 'deal-020',
    name: 'Observability Stack Migration',
    company: 'Pied Piper Inc',
    stage: 'Proposal',
    amount: 140000,
    owner: 'David Zhao',
    expectedClose: '2026-10-25',
    hubspotId: 'hs-deal-00901-b',
    notionPageId: 'notion-page-5590t',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '3 days ago',
    hubspotAmount: 140000,
    notionAmount: 140000,
    hubspotStage: 'Proposal',
    notionStage: 'Proposal'
  },
  {
    id: 'deal-021',
    name: 'Kubernetes Multi-Cluster Mgmt',
    company: 'Stark Logistics',
    stage: 'Negotiation',
    amount: 215000,
    owner: 'Elena Rostova',
    expectedClose: '2026-11-08',
    hubspotId: 'hs-deal-99012-b',
    notionPageId: 'notion-page-6601u',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '4 days ago',
    hubspotAmount: 215000,
    notionAmount: 215000,
    hubspotStage: 'Negotiation',
    notionStage: 'Negotiation'
  },
  {
    id: 'deal-022',
    name: 'Enterprise Search Integration',
    company: 'Acme Technologies',
    stage: 'Closed Won',
    amount: 105000,
    owner: 'Sarah Connor',
    expectedClose: '2026-08-15',
    hubspotId: 'hs-deal-88123-b',
    notionPageId: 'notion-page-7712v',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '4 days ago',
    hubspotAmount: 105000,
    notionAmount: 105000,
    hubspotStage: 'Closed Won',
    notionStage: 'Closed Won'
  },
  {
    id: 'deal-023',
    name: 'FinOps Optimization Pipeline',
    company: 'Globex Industries',
    stage: 'New Lead',
    amount: 58000,
    owner: 'Marcus Vance',
    expectedClose: '2026-12-20',
    hubspotId: 'hs-deal-77234-b',
    notionPageId: 'notion-page-8823w',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '5 days ago',
    hubspotAmount: 58000,
    notionAmount: 58000,
    hubspotStage: 'New Lead',
    notionStage: 'New Lead'
  },
  {
    id: 'deal-024',
    name: 'Automated Disaster Recovery',
    company: 'Cyberdyne Systems',
    stage: 'Proposal',
    amount: 185000,
    owner: 'Sarah Connor',
    expectedClose: '2026-11-14',
    hubspotId: 'hs-deal-66345-b',
    notionPageId: 'notion-page-9934x',
    hubspotStatus: 'synced',
    notionStatus: 'synced',
    syncStatus: 'In Sync',
    lastSyncedAt: '5 days ago',
    hubspotAmount: 185000,
    notionAmount: 185000,
    hubspotStage: 'Proposal',
    notionStage: 'Proposal'
  }
];

export const INITIAL_CONFLICTS: Conflict[] = [
  {
    id: 'conflict-001',
    dealId: 'deal-001',
    dealName: 'Enterprise Cloud Migration',
    company: 'Acme Technologies',
    field: 'amount',
    fieldLabel: 'Deal Value',
    hubspotValue: '$120,000',
    notionValue: '$115,000',
    lastSyncedValue: '$100,000',
    detectedAt: '12 mins ago',
    severity: 'critical',
    status: 'unresolved'
  },
  {
    id: 'conflict-002',
    dealId: 'deal-005',
    dealName: 'AI Infrastructure Contract',
    company: 'Cyberdyne Systems',
    field: 'stage',
    fieldLabel: 'Sales Pipeline Stage',
    hubspotValue: 'Negotiation',
    notionValue: 'Proposal',
    lastSyncedValue: 'Proposal',
    detectedAt: '35 mins ago',
    severity: 'high',
    status: 'unresolved'
  }
];

export const INITIAL_SYNC_EVENTS: SyncEvent[] = [
  {
    id: 'evt-1092',
    dealId: 'deal-001',
    dealName: 'Enterprise Cloud Migration',
    operation: 'conflict_detected',
    direction: 'bidirectional',
    result: 'conflict',
    version: 'v4.1.2-hs-nt',
    timestamp: '12 mins ago',
    details: 'Concurrent edit detected: HubSpot modified value to $120,000; Notion modified value to $115,000.',
    idempotencyKey: 'idemp-hs90812-mod-20260919',
    changedFields: {
      amount: { from: 100000, to: 'Conflict ($120k vs $115k)' }
    }
  },
  {
    id: 'evt-1091',
    dealId: 'deal-002',
    dealName: 'Data Analytics Platform',
    operation: 'update',
    direction: 'hubspot_to_notion',
    result: 'success',
    version: 'v4.1.0',
    timestamp: '24 mins ago',
    details: 'Stage updated from Qualified to Proposal. Notion database property synchronized in 142ms.',
    idempotencyKey: 'idemp-hs88231-prop-stage',
    changedFields: {
      stage: { from: 'Qualified', to: 'Proposal' }
    }
  },
  {
    id: 'evt-1090',
    dealId: 'deal-005',
    dealName: 'AI Infrastructure Contract',
    operation: 'conflict_detected',
    direction: 'bidirectional',
    result: 'conflict',
    version: 'v4.1.1-hs-nt',
    timestamp: '35 mins ago',
    details: 'Stage mismatch: HubSpot rep advanced stage to Negotiation while Notion SDR marked Proposal.',
    idempotencyKey: 'idemp-hs55431-stage-split',
    changedFields: {
      stage: { from: 'Proposal', to: 'Conflict (Negotiation vs Proposal)' }
    }
  },
  {
    id: 'evt-1089',
    dealId: 'deal-015',
    dealName: 'Customer Data Platform',
    operation: 'failed',
    direction: 'hubspot_to_notion',
    result: 'failed',
    version: 'v4.0.9',
    timestamp: '1 hour ago',
    details: 'Notion API 429 Rate Limit encountered during batch property write. Event queued for replay.',
    idempotencyKey: 'idemp-hs55456-err-ratelimit',
    errorDetails: 'HTTP 429: Rate limit exceeded (120 req/min). Retry-After: 30s'
  },
  {
    id: 'evt-1088',
    dealId: 'deal-003',
    dealName: 'Fleet Management System',
    operation: 'deduplicate',
    direction: 'fastn_engine',
    result: 'skipped',
    version: 'v4.0.8',
    timestamp: '1 hour ago',
    details: 'Duplicate webhook event received for hs-deal-77419. Idempotency filter matched hash. No write dispatched.',
    idempotencyKey: 'idemp-hs77419-dup-suppressed'
  },
  {
    id: 'evt-1087',
    dealId: 'deal-008',
    dealName: 'Logistics Automation',
    operation: 'update',
    direction: 'hubspot_to_notion',
    result: 'success',
    version: 'v4.0.7',
    timestamp: '5 hours ago',
    details: 'Deal marked Closed Won ($180,000). Notion page status updated, commission milestone triggered.',
    idempotencyKey: 'idemp-hs22789-won-sync'
  },
  {
    id: 'evt-1086',
    dealId: 'deal-009',
    dealName: 'Security Monitoring Platform',
    operation: 'create',
    direction: 'hubspot_to_notion',
    result: 'success',
    version: 'v4.0.6',
    timestamp: '6 hours ago',
    details: 'New deal record matched in Notion database: Page created with ID notion-page-3389i.',
    idempotencyKey: 'idemp-hs11890-create-init'
  }
];

export const INITIAL_FIELD_MAPPINGS: FieldMapping[] = [
  {
    id: 'map-01',
    hubspotField: 'dealname',
    hubspotType: 'Single-line text',
    notionProperty: 'Deal Name (Title)',
    notionType: 'Title',
    syncDirection: 'two_way',
    status: 'active'
  },
  {
    id: 'map-02',
    hubspotField: 'amount',
    hubspotType: 'Currency ($ USD)',
    notionProperty: 'Deal Value',
    notionType: 'Number (Currency)',
    syncDirection: 'two_way',
    status: 'active'
  },
  {
    id: 'map-03',
    hubspotField: 'dealstage',
    hubspotType: 'Enumeration / Pipeline Stage',
    notionProperty: 'Pipeline Stage',
    notionType: 'Select',
    syncDirection: 'two_way',
    status: 'active'
  },
  {
    id: 'map-04',
    hubspotField: 'hubspot_owner_id',
    hubspotType: 'User ID',
    notionProperty: 'Account Executive',
    notionType: 'Person / Select',
    syncDirection: 'one_way_to_notion',
    status: 'active'
  },
  {
    id: 'map-05',
    hubspotField: 'closedate',
    hubspotType: 'Date timestamp',
    notionProperty: 'Expected Close',
    notionType: 'Date',
    syncDirection: 'two_way',
    status: 'active'
  },
  {
    id: 'map-06',
    hubspotField: 'associated_company',
    hubspotType: 'Company association',
    notionProperty: 'Account / Organization',
    notionType: 'Relation / Text',
    syncDirection: 'two_way',
    status: 'active'
  }
];
